#!/usr/bin/env bash
# Nginx installation from listening on port 80.
# Nginx installation from listening on port 80.
# tool you need, start and destroy as many containers
# issue. Then, write a Bash script with the minimum
# automate

rm /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
