#!/usr/bin/env bash
# uses the while loop and the if, elif and else statments to display text.

i=1
while [ $i -le 8 ]
do
	i=$(( i + 1 ))
	echo "Best School"
	if [ $i -eq 4 ]
	then 
		echo "bad luck"
		continue
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		continue
	fi
done
